### ISSUE TITLE
Cool code! question about the modes and colors

### ISSUE THREAD

**Issue by eried** [AlexanderKlishin/msi-klm#1]
hi! what is the difference between gaming and normal?
and wave dual and breathe?
They seem to do the same inside your code :0

why the msi dragon center show so many color options? are they all "fake"?

**Comment by AlexanderKlishin** [comment]
Hi :) Thank you :)

Gaming mode highlights only small part of the keyboard, used in games.
Normal – highlights all keys.

Wave, dual and breathe have the same processing (switch (light_mode)), but different codes – so they are different.
* Wave – it’s a wave of lights – from left to right.
* Breathe – all leds “breathe” at the same time.
* Dual – I don`t remember exactly (unfortunately now I use another notebook) – but left, central and right part of the keyboard may have different colors.


About colors – unfortunately msi does provide any technical papers about this keyboard (checked 1 year ago).
I know only this 9 colors. But there are very strange parameter “-e N” %)
N – can be 1 2 or 3? As far as I remember.
It must manage intensity of the light. But … parameter also affects color …
I forget to mention this parameter in “usage”

**Comment by eried** [comment]
Thanks for answering. Yeah I understand what the modes do in the Dragon MSI app thing, but I was more asking about your code.

Anyhow, Dual works for me :) I made a little app that monitors some Ms Flow triggers, so I can have "six sense" for real life events. So I have spider sense now -sorta.

I was just wondering about why, thinking on a deeper secret rather than an incomplete code.

**Comment by AlexanderKlishin** [comment]
Oh %) sorry for my misunderstanding))

Wave, Breathe and Dual all have the same settings. And inside “switch (light_mode)” I set only different options. And options are the same - color, time and other.

Bu the most important is the line after switch statement, which turns on choosen effect:
“err = commit(handle, light_mode);”

This code looks like “reverse ingeneering and hacking” due to the lack of documentation ^)
